<a href="https://colab.research.google.com/github/Siripurapu-VighnaChaitanya/ML_practice_files/blob/main/ANN_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
ds=pd.read_csv('American Express.csv')

In [3]:
ds

Credit Score  Geography  Gender  Age  Customer Since  Current Account  \
0              553      Delhi  Female   45               4     0.000000e+00   
1              447  Bengaluru    Male   31               7     0.000000e+00   
2              501      Delhi  Female   32               2     0.000000e+00   
3              428      Delhi    Male   51               3     0.000000e+00   
4              492      Delhi  Female   57               6     1.912682e+06   
...            ...        ...     ...  ...             ...              ...   
9922           594  Bengaluru    Male   28               6     0.000000e+00   
9923           557  Bengaluru    Male   59               3     8.050490e+05   
9924           627     Mumbai  Female   42               4     1.893594e+06   
9925           600  Bengaluru  Female   51               0     9.031778e+05   
9926           553      Delhi    Male   75               7     0.000000e+00   

      Num of products  UPI Enabled  Estimated Yearly Income  Closed  
0                   4            1                   274150       0  
1                   4            1                   519360       0  
2                   4            1                   545501       0  
3                   4            1                    86868       0  
4                   2            1                   518680       0  
...               ...          ...                      ...     ...  
9922                4            1                   394810       0  
9923                2            0                    58163       1  
9924                4            0                   494067       0  
9925                2            1                   109375       1  
9926                4            1                   180031       0  

[9927 rows x 10 columns]

In [7]:
x=ds.iloc[:,0:-1].values
y=ds.iloc[:,-1].values

In [8]:
x

array([[553, 'Delhi', 'Female', ..., 4, 1, 274150],
       [447, 'Bengaluru', 'Male', ..., 4, 1, 519360],
       [501, 'Delhi', 'Female', ..., 4, 1, 545501],
       ...,
       [627, 'Mumbai', 'Female', ..., 4, 0, 494067],
       [600, 'Bengaluru', 'Female', ..., 2, 1, 109375],
       [553, 'Delhi', 'Male', ..., 4, 1, 180031]], dtype=object)

In [9]:
y

array([0, 0, 0, ..., 0, 1, 0])

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [15]:
x[:,[1,2]]

array([['Delhi', 0],
       ['Bengaluru', 1],
       ['Delhi', 0],
       ...,
       ['Mumbai', 0],
       ['Bengaluru', 0],
       ['Delhi', 1]], dtype=object)

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')

In [25]:
x=np.array(ct.fit_transform(x))

In [28]:
x[:,0:5]

array([[0.0, 1.0, 0.0, 553, 0],
       [1.0, 0.0, 0.0, 447, 1],
       [0.0, 1.0, 0.0, 501, 0],
       ...,
       [0.0, 0.0, 1.0, 627, 0],
       [1.0, 0.0, 0.0, 600, 0],
       [0.0, 1.0, 0.0, 553, 1]], dtype=object)

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [30]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [31]:
x_train

array([[ 0.99710782, -0.57768956, -0.57478135, ...,  0.90076321,
         0.64831965, -1.65601831],
       [ 0.99710782, -0.57768956, -0.57478135, ...,  0.90076321,
         0.64831965,  0.91709557],
       [ 0.99710782, -0.57768956, -0.57478135, ..., -0.94754703,
         0.64831965, -1.66264202],
       ...,
       [ 0.99710782, -0.57768956, -0.57478135, ...,  0.90076321,
        -1.54244901, -0.47285988],
       [-1.00290057, -0.57768956,  1.73979202, ...,  0.90076321,
         0.64831965,  1.08587937],
       [-1.00290057,  1.73103354, -0.57478135, ...,  0.90076321,
        -1.54244901,  1.34495412]])

In [32]:
x_test

array([[-1.00290057,  1.73103354, -0.57478135, ..., -0.94754703,
        -1.54244901, -0.0257341 ],
       [-1.00290057, -0.57768956,  1.73979202, ..., -0.94754703,
        -1.54244901, -1.59845179],
       [ 0.99710782, -0.57768956, -0.57478135, ..., -0.94754703,
         0.64831965,  0.91262044],
       ...,
       [-1.00290057, -0.57768956,  1.73979202, ...,  0.90076321,
        -1.54244901,  0.01585796],
       [-1.00290057,  1.73103354, -0.57478135, ..., -0.94754703,
         0.64831965, -0.49498764],
       [ 0.99710782, -0.57768956, -0.57478135, ..., -0.94754703,
         0.64831965, -0.33888551]])

In [33]:
ann_model=tf.keras.models.Sequential()
ann_model.add(tf.keras.Input(shape=(11,)))
ann_model.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann_model.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann_model.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
ann_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [34]:
ann_model.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.4780 - loss: 0.7383
Epoch 2/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8022 - loss: 0.4952
Epoch 3/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8000 - loss: 0.4575
Epoch 4/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7948 - loss: 0.4555
Epoch 5/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7965 - loss: 0.4422
Epoch 6/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7885 - loss: 0.4488
Epoch 7/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7944 - loss: 0.4408
Epoch 8/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7915 - loss: 0.4403
Epoch 9/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7952 - loss: 0.4392
Epoch 10/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7891 - loss: 0.4417
Epoch 11/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8060 - loss: 0.4147
Epoch 12/100
249/249 ━━━━━━━━━━━━━━━━━━━━

In [35]:
y_pred=ann_model.predict(x_test)
y_pred=(y_pred >0.5).astype(int)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [36]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [1 1]]


In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
import seaborn as sbo
cm = confusion_matrix(y_test, y_pred)
#sbo.heatmap(cm,annot=True)
print(cm)
accuracy_score(y_test, y_pred)

[[1498   75]
 [ 238  175]]


0.8423967774420946